on: 
  push:
    branches:
      - master

jobs: 
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.0.1

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: sass --watch input.scss output.css

      - name: add commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . --force
          git commit -m "build: $GITHUB_SHA"
          git push
