on: 
  push:
    branches:
      - master
    # tags:
    #   - v*

env:
  INPUT_FILE: input.scss
  OUTPUT_FILE: test/output.css

jobs: 
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.0.1

      - name: Install SASS
        run: npm install -g sass

      - name: Build
        run: sass ${{ env.INPUT_FILE }}:${{ env.OUTPUT_FILE }}

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ env.OUTPUT_FILE }} --force
          git commit -m "Build: ${{ github.event.head_commit.message }}" --author "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" | echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}