on: 
  push:
    branches:
      - master

jobs: 
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.0.1

      - name: Install SASS
        run: npm install -g sass

      - name: Build
        run: sass input.scss:output.css

      - name: add commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build SASS"
          branch: ${{ github.ref }}
          commit_options: '--force'